- README.md
- docs/installation.md
- frontend/src/pages/Audits/GraphsBlock/MetricModal/MetricModal.style.ts
This PR resolves #21 
For information, column-count is supported by all main browsers : 
Good to know: It will support more items without CSS modifications ;)
> Fix the perf metrics modal layout

- frontend/public/font.css
- frontend/public/index.html
> Fix IBM Plex font not loaded

- CHANGELOG.md
- Dockerfile
- backend/root/settings/prod.py
- start_backend.sh
Fixes #61 
Create a dedicated user for running Celery.
> Create a dedicated app user

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/docs.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/pull_request_template.md
This is a first setup of #72.
Many thanks to the Angular Components setup for GitHub issues.
> feat: setup github issues and pull request templates

- README.md
> Add Heroku Teams deploy instructions to the README

- docs/package.json
- docs/src/pages/index.js
- docs/yarn.lock
The latest update for the alpha version of Docusaurus includes performance improvements, bug fixes and new features. Detailed changelog: https://github.com/facebook/docusaurus/blob/master/CHANGELOG-2.x.md#docusaurus-2-changelog
> Bump docusaurus to 2.0.0-alpha.32

- docs/package.json
- docs/yarn.lock
Changelog: https://github.com/facebook/docusaurus/blob/master/CHANGELOG-2.x.md
> Upgrade docusaurus to 2.0.0-alpha.39

- frontend/src/components/Root/Root.tsx
> fix: add english as default translation language

- frontend/src/pages/Audits/AnalyticsBlock/WebPageTestBlock/WebPageTestBlock.tsx
> Fix WPT Compare view for Private Instances

- backend/audits/views.py
> Fix `from_date` not working for scripts

- backend/audits/wpt_utils/normalizer.py
- backend/projects/templates/admin/projects/project_action.html
> Fix time to interactive metric

- docs/docusaurus.config.js
This PR adds Algolia DocSearch (through the Docusaurus integration) to the docs website.
> Add Algolia DocSearch to docs website

- frontend/src/components/Root/components/Menu/components/ProjectMenuContent/ProjectMenuContent.style.ts
> [Refactoring] Replace overflow:scroll with auto on AuditsAndScriptsContainer

- frontend/src/translations/fa.json
I translate Falco to Farsi ([Persian language](https://en.wikipedia.org/wiki/Persian_Wikipedia))
> Translate to fa

- frontend/src/translations/en.json
> #120 Fix translation

- .circleci/config.yml
- frontend/src/icons/Add/Add.tsx
- frontend/src/icons/Checkmark/Checkmark.tsx
- frontend/src/icons/Close/Close.tsx
- frontend/src/icons/Information/Information.tsx
- frontend/src/icons/MenuArrow/MenuArrow.tsx
Fixed a bunch of innocuous (but annoying) errors in the console due to malformed SVG properties.
> Fix warnings in console due to improper SVG properties

- docs/package.json
- docs/yarn.lock
Bumping docusaurus and react to latest
> [chore][docs] Update docusaurus and react versions

- CONTRIBUTING.md
- Makefile
- backend/Pipfile
- backend/Pipfile.lock
- backend/audits/factories.py
- backend/core/factories.py
- backend/core/management/commands/load_fixtures.py
- backend/projects/factories.py
- postdeploy.sh
Closes #133 
These fixtures create a project with two pages, in two environments, for two users (one admin, the other regular) and populates audits for the last 30 days. Should be enough to start with!
> Better fixtures for local development & Review Apps

- backend/core/factories.py
- backend/core/serializers.py
- frontend/src/components/Root/components/Header/components/AccountMenu/AccountMenu.tsx
- frontend/src/redux/user/modelizer.ts
- frontend/src/redux/user/reducer.ts
- frontend/src/redux/user/types.ts
- frontend/src/translations/en.json
- frontend/src/translations/fa.json
- frontend/src/translations/fr.json
> Add link to admin interface

- Makefile
- docker-compose.yml
- hooks/pre-commit
Hello,
I encountered some issues while installing the project, I think this PR will make the installation smoother. 
> update install script and dev environement

- docs/docs/getting-started/configuring-your-first-project.md
> fix typo in word "launch" in documentation

- frontend/public/reset.css
- frontend/src/components/Button/Button.style.tsx
- frontend/src/components/Button/index.tsx
- frontend/src/components/MessagePill/MessagePill.style.ts
- frontend/src/components/MessagePill/MessagePill.tsx
- frontend/src/components/MetricGraph/MetricGraph.style.tsx
- frontend/src/components/MetricGraph/MetricGraph.tsx
- frontend/src/components/MetricTooltip/MetricTooltip.tsx
- frontend/src/components/Root/components/Header/Header.style.ts
- frontend/src/components/Root/components/Header/Header.tsx
- frontend/src/components/Root/components/Header/components/AccountMenu/AccountMenu.style.ts
- frontend/src/components/Root/components/Header/components/AccountMenu/AccountMenu.tsx
- frontend/src/components/Root/components/Header/components/ProjectsMenu/ProjectsMenu.style.ts
- frontend/src/components/Root/components/Menu/components/ProjectSettingsMenuContent/ProjectSettingsMenuContent.style.ts
- frontend/src/components/Root/components/Menu/components/ProjectSettingsMenuContent/ProjectSettingsMenuContent.tsx
- frontend/src/pages/Audits/AnalyticsBlock/WebPageTestBlock/WebPageTestBlock.style.tsx
- frontend/src/pages/Audits/GraphsBlock/GraphModal/GraphModal.style.ts
- frontend/src/pages/Audits/GraphsBlock/GraphsBlock.style.tsx
- frontend/src/pages/Audits/GraphsBlock/MetricModal/MetricModal.style.ts
- frontend/src/pages/EnvironmentSettings/Components/AuditParameterTable/AuditParameterTable.style.tsx
- frontend/src/pages/EnvironmentSettings/EnvironmentSettings.style.tsx
- frontend/src/pages/PagesAndScriptsSettings/Components/PageTable/PageTable.style.tsx
- frontend/src/pages/PagesAndScriptsSettings/Components/ScriptTable/ScriptModal/ScriptModal.style.ts
- frontend/src/pages/PagesAndScriptsSettings/Components/ScriptTable/ScriptTable.style.tsx
- frontend/src/pages/PagesAndScriptsSettings/PagesAndScriptsSettings.style.tsx
- frontend/src/pages/User/Form.style.tsx
- frontend/src/pages/sharedStyle.style.tsx
- frontend/src/stylesheet.ts
Add outline on all clickable elements for keyboard navigation
Issue Number: 146
Closes : https://github.com/theodo/falco/issues/146
> [#146] add outline on all clickable elements

- docs/docs/getting-started/configuring-your-first-project.md
> [documentation] update documentation to configure your first project

- frontend/src/components/Loader/Loader.style.ts
- frontend/src/components/Loader/Loader.tsx
- frontend/src/components/MetricTooltip/MetricTooltip.style.tsx
- frontend/src/components/MetricTooltip/MetricTooltip.tsx
- frontend/src/components/Welcome/Welcome.style.tsx
- frontend/src/components/Welcome/Welcome.tsx
- frontend/src/pages/Audits/AnalyticsBlock/AnalyticsBlock.style.tsx
- frontend/src/pages/Audits/AnalyticsBlock/AnalyticsBlock.tsx
- frontend/src/pages/Audits/AnalyticsBlock/WebPageTestBlock/WebPageTestBlock.style.tsx
- frontend/src/pages/Audits/AnalyticsBlock/WebPageTestBlock/WebPageTestBlock.tsx
- frontend/src/pages/Audits/GraphsBlock/GraphsBlock.style.tsx
- frontend/src/pages/Audits/GraphsBlock/GraphsBlock.tsx
- frontend/src/pages/Audits/GraphsBlock/MetricModal/MetricModal.style.ts
- frontend/src/pages/Audits/GraphsBlock/MetricModal/MetricModal.tsx
- frontend/src/pages/Audits/GraphsBlock/MetricModal/MetricName/MetricName.style.ts
- frontend/src/pages/Audits/GraphsBlock/MetricModal/MetricName/MetricName.tsx
- frontend/src/pages/EnvironmentSettings/EnvironmentSettings.style.tsx
- frontend/src/pages/EnvironmentSettings/EnvironmentSettings.tsx
- frontend/src/pages/GeneralSettings/GeneralSettings.style.tsx
- frontend/src/pages/GeneralSettings/GeneralSettings.tsx
- frontend/src/pages/MembersSettings/MembersSettings.style.tsx
- frontend/src/pages/MembersSettings/MembersSettings.tsx
- frontend/src/pages/PagesAndScriptsSettings/PagesAndScriptsSettings.style.tsx
- frontend/src/pages/PagesAndScriptsSettings/PagesAndScriptsSettings.tsx
- frontend/src/pages/Project/Project.style.tsx
- frontend/src/pages/Project/Project.tsx
- frontend/src/pages/Projects/Projects.style.tsx
- frontend/src/pages/Projects/Projects.tsx
> use multi exports for styles

- frontend/src/components/Root/components/Header/Header.style.ts
- frontend/src/components/Root/components/Header/Header.tsx
- frontend/src/components/Root/components/Header/components/AccountMenu/AccountMenu.style.ts
- frontend/src/components/Root/components/Header/components/AccountMenu/AccountMenu.tsx
- frontend/src/components/Root/components/Header/components/ProjectsMenu/ProjectsMenu.style.ts
- frontend/src/components/Root/components/Header/components/ProjectsMenu/ProjectsMenu.tsx
> Refacto and simplify header menu

- frontend/.env.example
- frontend/Dockerfile.heroku.static
- frontend/package.json
- frontend/src/components/Root/components/Menu/components/ProjectMenuContent/ProjectMenuContent.tsx
- frontend/src/pages/Audits/AnalyticsBlock/AnalyticsBlock.style.tsx
- frontend/src/pages/GeneralSettings/GeneralSettings.style.tsx
- frontend/tsconfig.json
- frontend/tsconfig.paths.json
> Clean frontend imports and node settings

- frontend/src/components/Root/components/Header/components/ProjectsMenu/ProjectsMenu.tsx
> add empty alt attribute on images in project menu

- frontend/src/components/Root/components/Header/Header.style.ts
- frontend/src/components/Root/components/Header/Header.tsx
Issue Number: [#170](https://github.com/theodo/falco/issues/170)
> Make "Docs" and "Admin Interface" clickable again

- frontend/src/components/Root/components/Header/Header.tsx
- frontend/src/components/Root/components/Header/Header.wrap.tsx
- frontend/src/components/Root/components/Header/components/AccountMenu/AccountMenu.tsx
- frontend/src/components/Root/components/Header/components/AccountMenu/AccountMenu.wrap.tsx
> Correctly display "Manage Project Settings" button

- frontend/src/components/Root/Root.style.ts
- frontend/src/components/Root/Root.tsx
- frontend/src/stylesheet.ts
- frontend/src/translations/en.json
- frontend/src/translations/fa.json
- frontend/src/translations/fr.json
> Add a “Skip to content” link, accessible to the keyboard

- frontend/src/pages/Audits/AnalyticsBlock/LighthouseBlock/LighthouseMetrics/LighthouseMetrics.tsx
> Fix no key warning

- frontend/src/components/MetricGraph/MetricGraph.tsx
Issue Number: [#153](https://github.com/theodo/falco/issues/153)
> Customize graphs color

- backend/Pipfile
- backend/Pipfile.lock
> Revert "Bump django from 3.0.3 to 3.0.7 in /backend"

- backend/projects/admin.py
> add wpt_instance_url as filter in project admin

- frontend/yarn.lock
> Revert "Update packages versions"

- backend/audits/views.py
- backend/core/management/commands/load_fixtures.py
- backend/core/middlewares.py
> use django timezone instead of naive datetimes

- docs/docs/getting-started/installation.mdx
this is helpful when using an external postgres instance, rather than the one instantiated via docker-compose.
Issue Number: #109
> make syntax of db env var explicit

- frontend/src/pages/Audits/AnalyticsBlock/LighthouseBlock/LighthouseMetrics/LighthouseMetrics.tsx
- frontend/src/redux/auditResults/__tests__/sagas.test.ts
- frontend/src/redux/auditResults/modelizer.ts
- frontend/src/redux/auditResults/types.ts
- frontend/src/services/networking/request.ts
> rename camel-case variables

- frontend/src/pages/Audits/AnalyticsBlock/WebPageTestBlock/WebPageTestBlock.wrap.tsx
- frontend/src/pages/Audits/AnalyticsBlock/WebPageTestBlock/__tests__/WebPageTestBlock.test.tsx
- frontend/src/pages/Audits/AnalyticsBlock/WebPageTestBlock/index.ts
> fix tests on webpagetest block

- frontend/src/components/Root/Root.tsx
> remove explicit any in Root.tsx

- frontend/src/components/Select/Select.tsx
- frontend/src/pages/EnvironmentSettings/Components/AuditParameterTable/AddAuditParameterRow/AddAuditParameterRow.tsx
- frontend/src/pages/EnvironmentSettings/Components/AuditParameterTable/AuditParameterRow/AuditParameterRow.tsx
- frontend/src/pages/GeneralSettings/Components/ProjectDetailsInput/ProjectDetailsInput.tsx
> correctly type react-select

- backend/audits/models.py
> add audit parameters on audit __str__

- backend/audits/tasks.py
> Fail repeat audits

- backend/audits/models.py
- backend/audits/tasks.py
- backend/audits/views.py
- backend/core/management/commands/populate-periodic-tasks.py
> Clean unfinished audits

- README.md
- backend/core/tests/management/commands/test_populateperiodictasks.py
> fix deployment tests + deploy version

- CHANGELOG.md
- docs/docs/getting-started/installation.mdx
- docs/src/pages/index.js
> clean docs to adapt release 1.1.5

- docs/docusaurus.config.js
- docs/yarn.lock
> upgrade docs packages

- backend/projects/admin.py
- backend/projects/forms.py
- backend/projects/models.py
> Move ScriptForm from models to forms

- backend/audits/models.py
- backend/audits/tasks.py
- backend/audits/wpt_utils/wpt_request_builder.py
> clean tasks: factorize audit page or script extraction

- frontend/yarn.lock
> upgrade frontend packages

- backend/projects/views.py
Closes https://github.com/theodo/falco/issues/236
> fix: return has_siblings to non-admin-users

- backend/audits/admin.py
> feat: add custom instance filter on audits

- docker-compose.prod.yml
> feat: bump redis version to 6.2

- .circleci/config.yml
- Dockerfile
- backend/Dockerfile
- backend/Pipfile
- backend/Pipfile.lock
> fix: bump python to 3.8 and django to 3.2

- backend/core/tests/test_models.py
> fix: remove abstract model test

- backend/audits/models.py
> feat: update json field import (fix warning)

- CHANGELOG.md
- README.md
- docs/docs/getting-started/installation.mdx
- docs/src/pages/index.js
> docs: 1.2.0 release docs

- backend/audits/tasks.py
- backend/audits/wpt_utils/normalizer.py
> feat: simplify modelizer

- CHANGELOG.md
- README.md
- docs/docs/getting-started/installation.mdx
- docs/src/pages/index.js
- frontend/src/components/Root/components/Header/Header.tsx
> fix: display projects menu
